apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-4d55"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-4d55"
  template:
    metadata:
      labels:
        app: "myaks-4d55"
    spec:
      containers:
        - name: "myaks-4d55"
          image: "mydevacr.azurecr.io/myaks"
          ports:
          - containerPort: 5000