apiVersion: v1
kind: Service
metadata:
    name: "myaks-4d55"
    labels:
        app: "myaks-4d55"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "myaks-4d55"